### ISSUE TITLE
Key Error <pad>

### ISSUE THREAD

**Issue by architlatkar27** [Parth27/Data2Text#1]
Hello there, I was trying to run this project on colab. I was able to successfully install the requirements. When I ran the preprocess.py file, i got the following error - 
```
Traceback (most recent call last):
  File "preprocess.py", line 172, in <module>
    X_fields,X_inputs,y = prep_data(labeled_fields,inputs,text,labels)
  File "preprocess.py", line 159, in prep_data
    pads = [vocab['<pad>'] for x in range(max_input_len-len(inputs[i]))]
  File "preprocess.py", line 159, in <listcomp>
    pads = [vocab['<pad>'] for x in range(max_input_len-len(inputs[i]))]
KeyError: '<pad>'
```

How can i resolve this issue.

**Comment by nameless0704** [comment]
Can you run this code entirely?
